### ISSUE TITLE
Unsatisfied Python dependency

### ISSUE THREAD

**Issue by chleggett** [chleggett/homebrew-gr-osmosdr#1]
install requires the python cheetah package to installed. otherwise, the build fails.

**Comment by Bondrake** [comment]
Was receiving this failure:
[ 77%] Built target gnuradio-osmosdr
make: *** [all] Error 2
couldn't understand kern.osversion `14.1.0'

Did "pip install cheetah", tried again, and it worked.

Error posted for searchability.

**Comment by Stevancw** [comment]
You hero - thanks so much!

**Comment by megrimm** [comment]
yup that worked... thanks!

**Comment by lordkev** [comment]
:+1:
