### ISSUE TITLE
errors when linking libgnuradio-osmosdr.dylib

### ISSUE THREAD

**Issue by nguillermin** [chleggett/homebrew-gr-osmosdr#2]
Undefined symbols for architecture x86_64:
      "_rtlsdr_get_index_by_serial", referenced from:
          rtl_source_c::rtl_source_c(std::__1::basic_string<char, std::__1::char_traits<char>,     std::__1::allocator<char> > const&) in rtl_source_c.cc.o
      "_rtlsdr_set_agc_mode", referenced from:
          rtl_source_c::rtl_source_c(std::__1::basic_string<char, std::__1::char_traits<char>,     std::__1::allocator<char> > const&) in rtl_source_c.cc.o
          rtl_source_c::set_gain_mode(bool, unsigned long) in rtl_source_c.cc.o
      "_rtlsdr_set_direct_sampling", referenced from:
          rtl_source_c::rtl_source_c(std::__1::basic_string<char, std::__1::char_traits<char>,     std::__1::allocator<char> > const&) in rtl_source_c.cc.o
      "_rtlsdr_set_offset_tuning", referenced from:
          rtl_source_c::rtl_source_c(std::__1::basic_string<char, std::__1::char_traits<char>,     std::__1::allocator<char> > const&) in rtl_source_c.cc.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [lib/libgnuradio-osmosdr.0.1.4.dylib] Error 1
    make[1]: *** [lib/CMakeFiles/gnuradio-osmosdr.dir/all] Error 2
    make: *** [all] Error 2

Trying to compile against libstdc++ gives me even more errors.

**Comment by chleggett** [comment]
Has anyone else seen this? I cannot reproduce it.

**Comment by chleggett** [comment]
I haven't heard from anyone else having this issue. @nguillermin let me know if you are still having the trouble and I will reopen, but for now I am going to close this issue.
